### ISSUE TITLE
Error on npm install

### ISSUE THREAD

**Issue by luandro** [conor-mac-aoidh/express-pouchdb-replication-stream#7]
```
9 errors generated.
make: *** [Release/obj.target/leveldown/src/batch.o] Error 1
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/Users/me/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:270:23)
gyp ERR! stack     at emitTwo (events.js:87:13)
gyp ERR! stack     at ChildProcess.emit (events.js:172:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Darwin 14.5.0
gyp ERR! command "/Users/me/.nvm/versions/node/v4.2.3/bin/node" "/Users/me/.nvm/versions/node/v4.2.3/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/me/project/node_modules/express-pouchdb-replication-stream/node_modules/pouchdb/node_modules/leveldown
gyp ERR! node -v v4.2.3
gyp ERR! node-gyp -v v3.0.3
gyp ERR! not ok
```

Getting a big list of errors when trying to install via NPM...

**Comment by luandro** [comment]
NVM, seems to have worked.
